### PR TITLE
pep8 pass

### PR DESCRIPTION
**Pull request by bignaux**

### CODE REVIEW

**Comment by souvik1997** [comment]
Thanks for the pull request. Did you manually edit the file to comply with pep8 or did you use a program?

I'm asking because the diff is huge.

**Comment by souvik1997** [comment]
Additionally, your file doesn't follow E501 (line too long error).

**Comment by bignaux** [comment]
i manually did it after pydev formatting (tab spacing). I'm ignoring E501 since i'm not totally agree with 80 char limitation ... It's huge because you were using tab spacing. There is still some work, like 'type' variable, a reserved keyword, useless import. But i prefer see step by step how contributions are received before spend too much time. This patch contains no change code.

**Comment by souvik1997** [comment]
Thanks for the contribution!

**Pull request merged**
